# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

Exception: File `'initialise.py'` not found.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)#注意两个下划线
np.show_config()

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/prosper/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/prosper/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/prosper/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/prosper/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/prosper/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/prosper/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/prosper/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/prosper/opt/anaconda3/include']


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
np.size(z)

10

In [7]:
import sys
sys.getsizeof(z)

184

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7fb6107007f0>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
q=np.arange(10,50)#注意要到50
q

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
Q=np.array(q[::-1])
Q

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
w=np.arange(9).reshape(3,3)
w

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
e=np.array([1,2,0,0,4,0])
e
r=np.nonzero(e)
r

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
t=np.eye(3,3)
t

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
y=np.random.random((3,3,3))
y

array([[[0.9798006 , 0.69576871, 0.11532464],
        [0.26516775, 0.8339623 , 0.812942  ],
        [0.16262561, 0.06845234, 0.7218591 ]],

       [[0.65926762, 0.17577771, 0.44838888],
        [0.02786492, 0.63121334, 0.74714415],
        [0.41654471, 0.95595551, 0.26602814]],

       [[0.86108856, 0.18813145, 0.07966594],
        [0.83757795, 0.58019444, 0.48111325],
        [0.02460891, 0.53664045, 0.86522552]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
u=np.min(np.random.random((10,10)))
u

0.005183679005773989

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
o=np.mean(np.random.random(30))
o

0.5953175167884984

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
p=np.ones((10,10))
p[1:-1,1:-1]=0
p

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
a=np.ones((10,10))
np.pad(a,pad_width=1,mode='constant',constant_values='8')
a[:, [0, -1]] = 0
a[[0, -1], :] = 0
print
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [20]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
s=np.diag(1+np.arange(5),k=1)
s

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
d=np.zeros((8,8),dtype=int)
d[1::2,::2]=1
d[::2,1::2]=1
d

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [23]:
print(np.unravel_index(100,((6,7,8))))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [24]:
f=np.tile( np.array([[0,2,3],[2,3,0]]),(1,2))
  #np.tile( np.array([[0,1],[1,0]]),(4,4))
f

array([[0, 2, 3, 0, 2, 3],
       [2, 3, 0, 2, 3, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [25]:
g=np.random.standard_normal((5,5))
g

array([[ 1.20709817,  0.30445741, -0.95932979,  1.00921913,  0.50399422],
       [ 0.35325988, -0.73171967, -0.2361829 ,  1.20753108, -0.91889079],
       [-1.49817846, -1.91642276, -0.24885843,  0.3425721 , -0.43299397],
       [ 1.13192921, -0.15703515, -2.09999889, -0.37548213,  0.37529304],
       [ 1.37305241, -0.4012656 , -0.92567234,  2.00315374, -0.06350543]])

In [26]:
G=np.random.random((5,5))
G=(G-np.mean(G))/(np.std(G))
G

array([[-1.5093945 , -0.20780714,  1.2511562 , -0.72943909,  0.34820702],
       [ 0.40932857, -1.32255189,  0.81803492,  0.21557597, -0.31930428],
       [ 1.48441637,  0.25188193,  0.73562078, -1.63196139,  1.34361588],
       [-0.8097039 ,  0.10747404,  0.88328267,  1.36605396, -0.99642418],
       [-0.30887556, -1.45131216,  1.21463582,  0.3807966 , -1.52330663]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [38]:
Q=np.ones((5,3))
F=np.ones((3,2))
M=np.dot(Q,F)
M

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [59]:
Z=np.arange(11)
Z[(3 < Z) & (Z < 8)]*= -1
#Z[(3 < Z) & (Z < 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [62]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [70]:
#2 << Z >> 2
#Z <- Z
#1j*Z
#Z/1/1

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [71]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/cp/fjnzctrx54j3s77m7db2p3n40000gn/T/ipykernel_26481/548293649.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
/var/folders/cp/fjnzctrx54j3s77m7db2p3n40000gn/T/ipykernel_26481/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [129]:
Z = np.random.uniform(-10,+10,10)
Z

array([-7.02782409, -6.83292381, -3.56026834,  2.85961379,  8.52189956,
        4.74727325,  9.1975905 ,  5.94533131,  2.38351718, -0.15405926])

In [137]:
np.where(Z>0)

(array([3, 4, 5, 6, 7, 8]),)

In [138]:
np.ceil(Z)

array([-7., -6., -3.,  3.,  9.,  5., 10.,  6.,  3., -0.])

In [139]:
np.floor(Z)

array([-8., -7., -4.,  2.,  8.,  4.,  9.,  5.,  2., -1.])

In [144]:
np.where(Z>0, np.ceil(Z), np.floor(Z))


array([-8., -7., -4.,  3.,  9.,  5., 10.,  6.,  3., -1.])

In [131]:
np.abs(Z)

array([7.02782409, 6.83292381, 3.56026834, 2.85961379, 8.52189956,
       4.74727325, 9.1975905 , 5.94533131, 2.38351718, 0.15405926])

In [133]:
np.ceil(np.abs(Z))

array([ 8.,  7.,  4.,  3.,  9.,  5., 10.,  6.,  3.,  1.])

In [134]:
np.copysign(np.ceil(np.abs(Z)), Z)

array([-8., -7., -4.,  3.,  9.,  5., 10.,  6.,  3., -1.])

In [130]:
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-8. -7. -4.  3.  9.  5. 10.  6.  3. -1.]


In [135]:
#More readable
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-8. -7. -4.  3.  9.  5. 10.  6.  3. -1.]


In [80]:
a=np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

#### 30. How to find common values between two arrays? (★☆☆)

In [105]:
a[1,0,3]#对应reshape括号内

15

In [146]:
# 30. How to find common values between two arrays?

np.intersect1d([1,7,9,6],[1,9,5,2])

array([1, 9])

In [159]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)#(low, high=None, size=None, dtype=’l’)
Z1

7

# 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [161]:
# Suicide mode on
#defaults = np.seterr(all="ignore")
#Z = np.ones(1) / 0

# Back to sanity
#_ = np.seterr(**defaults)

# Equivalently with a context manager
#with np.errstate(all="ignore"):
    np.arange(3) / 0

In [114]:
a[:,-19:10,:]#注意超过当使用范围，矩阵内最大行/列数算

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
#31. How to ignore all numpy warnings (not recommended)? 


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [126]:
a=np.emath.sqrt(2j)
a

(1+1j)

In [127]:
c=np.emath.sqrt(1j)
c

(0.7071067811865476+0.7071067811865475j)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [165]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
today

numpy.datetime64('2022-03-26')

In [166]:
yesterday

numpy.datetime64('2022-03-25')

In [167]:
tomorrow

numpy.datetime64('2022-03-27')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [168]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [193]:
A = np.ones(3)*1
A
B = np.ones(3)*2
B
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [204]:
np.random.randint(0,8,9)
np.random.random(10)
np.ceil(np.random.standard_normal(5))
Z=np.random.uniform(10,10,10)
#Z-Z%1
#Z//1
#np.floor(Z)
Z.astype(int)
np.trunc(Z)

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [219]:
a=np.arange(0,5)
b=np.array(([a,a,a,a,a]))
b

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [223]:
Z = np.zeros((5,5))
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [228]:
a=np.arange(5,5)
#b=np.tile((a,1,5))
b

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [239]:
np.tile(np.arange(0, 5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [248]:
def fun():
    for x in range(9):
        yield x
Z = np.fromiter(fun(),dtype=float,count=-1)
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

<generator object <genexpr> at 0x7fb620bba120>

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [271]:
np.linspace(0,1,num=11,endpoint=False,retstep=False,dtype=float,axis=0)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [267]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [281]:
sort(np.random.random(10))

array([0.17731139, 0.19175242, 0.33643851, 0.46854816, 0.47946966,
       0.48701908, 0.6500023 , 0.65341207, 0.71487513, 0.91508621])

In [280]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.23997294 0.28994969 0.35764941 0.37527628 0.5118239  0.53551386
 0.67890594 0.71325848 0.71680736 0.9997007 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [282]:
np.add.reduce(np.arange(10))

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [284]:
A=np.random.random(10)
B=np.random.random(10)
np.allclose(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [285]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [292]:
Z = np.random.random((10,2))
Z

array([[0.28072271, 0.93299384],
       [0.56819359, 0.80168774],
       [0.22474403, 0.44476788],
       [0.14860987, 0.58950676],
       [0.79076374, 0.27643695],
       [0.82402162, 0.29030481],
       [0.39190393, 0.63427633],
       [0.02745478, 0.48001215],
       [0.43457567, 0.50554542],
       [0.19609034, 0.59869521]])

In [293]:
X,Y = Z[:,0], Z[:,1]
X

array([0.28072271, 0.56819359, 0.22474403, 0.14860987, 0.79076374,
       0.82402162, 0.39190393, 0.02745478, 0.43457567, 0.19609034])

In [294]:
Y

array([0.93299384, 0.80168774, 0.44476788, 0.58950676, 0.27643695,
       0.29030481, 0.63427633, 0.48001215, 0.50554542, 0.59869521])

In [295]:
Z = np.sqrt(X**2+Y**2)
Z

array([0.97431143, 0.9826226 , 0.49832554, 0.60794992, 0.83769009,
       0.87366384, 0.74558376, 0.48079666, 0.66665747, 0.62998998])

In [296]:
T = np.arctan2(Y,X)
T

array([1.27852893, 0.95422414, 1.10291266, 1.3238498 , 0.33630258,
       0.3387245 , 1.01733652, 1.51366257, 0.86074526, 1.25427829])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [311]:
z=np.random.random(10)
z[z.argmax()]=0
z

array([0.96930667, 0.58990169, 0.        , 0.15253543, 0.35305482,
       0.78181907, 0.17527876, 0.07289075, 0.36750544, 0.06188235])

In [306]:
two_dim_array = np.array([[1, 3, 5], [0, 4, 3]])
max_index_axis1 = np.argmax(two_dim_array, axis = 1)
max_index_axis1 

array([2, 1])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [312]:
np.meshgrid([0,1],[0,1])

[array([[0, 1],
        [0, 1]]),
 array([[0, 0],
        [1, 1]])]

In [319]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [320]:
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

In [321]:
np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))

[array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ]]),
 array([[0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.25, 0.25, 0.25, 0.25, 0.25],
        [0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
        [0.75, 0.75, 0.75, 0.75, 0.75],
        [1.  , 1.  , 1.  , 1.  , 1.  ]])]

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [322]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [323]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [330]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)

-128
-2147483648
-9223372036854775808


In [331]:
print(np.iinfo(dtype).max)

9223372036854775807


In [326]:
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)

-3.4028235e+38
-1.7976931348623157e+308


In [327]:
print(np.finfo(dtype).max)

1.7976931348623157e+308


In [328]:
print(np.finfo(dtype).eps)

2.220446049250313e-16


In [325]:
help(np.iinfo)

Help on class iinfo in module numpy:

class iinfo(builtins.object)
 |  iinfo(int_type)
 |  
 |  iinfo(type)
 |  
 |  Machine limits for integer types.
 |  
 |  Attributes
 |  ----------
 |  bits : int
 |      The number of bits occupied by the type.
 |  min : int
 |      The smallest integer expressible by the type.
 |  max : int
 |      The largest integer expressible by the type.
 |  
 |  Parameters
 |  ----------
 |  int_type : integer type, dtype, or instance
 |      The kind of integer data type to get information about.
 |  
 |  See Also
 |  --------
 |  finfo : The equivalent for floating point data types.
 |  
 |  Examples
 |  --------
 |  With types:
 |  
 |  >>> ii16 = np.iinfo(np.int16)
 |  >>> ii16.min
 |  -32768
 |  >>> ii16.max
 |  32767
 |  >>> ii32 = np.iinfo(np.int32)
 |  >>> ii32.min
 |  -2147483648
 |  >>> ii32.max
 |  2147483647
 |  
 |  With instances:
 |  
 |  >>> ii32 = np.iinfo(np.int32(10))
 |  >>> ii32.min
 |  -2147483648
 |  >>> ii32.max
 |  2147483647
 |  
 

#### 49. How to print all the values of an array? (★★☆)

In [334]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [346]:
np.set_printoptions(threshold=float(7))
C=np.arange(10)
C

array([0,
       1,
       2,
       ...,
       7,
       8,
       9])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [347]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

95


In [348]:
index

95

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)